
// Notification
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const FETCH_NOTIFIACTIONS_PENDING = 'FETCH_NOTIFIACTIONS_PENDING';
export const FETCH_NOTIFIACTIONS_REJECTED = 'FETCH_NOTIFIACTIONS_REJECTED';
export const FETCH_NOTIFIACTIONS_FULFILLED = 'FETCH_NOTIFIACTIONS_FULFILLED';
